In [111]:
import pandas as pd

In [112]:
df = pd.read_csv('rawg_games_20k_with_images.csv')

In [113]:
df.shape

(20000, 14)

In [114]:
df_copy = df.copy()

In [115]:
df_copy.columns.tolist()

['id',
 'name',
 'slug',
 'released',
 'metacritic',
 'rating',
 'ratings_count',
 'platforms',
 'genres',
 'stores',
 'added',
 'tags',
 'background_image',
 'background_image_additional']

In [116]:
req_cols = ['id', 'name', 'released', 'rating', 'platforms', 'genres', 'tags','background_image']
df_req_cols = df_copy[req_cols]

In [117]:
df_req_cols

,id,name,released,rating,platforms,genres,tags,background_image
0,3498,Grand Theft Auto V,2013-09-17,4.47,PC|PlayStation 5|Xbox Series S/X|PlayStation 4...,Action,Singleplayer|Steam Achievements|Multiplayer|Fu...,https://media.rawg.io/media/games/20a/20aa03a1...
1,3328,The Witcher 3: Wild Hunt,2015-05-18,4.64,PlayStation 5|Xbox Series S/X|macOS|PlayStatio...,Action|RPG,Singleplayer|Full controller support|Atmospher...,https://media.rawg.io/media/games/618/618c2031...
2,4200,Portal 2,2011-04-18,4.58,PlayStation 3|PC|Xbox 360|Linux|macOS|Xbox One,Shooter|Puzzle,Singleplayer|Steam Achievements|Multiplayer|Fu...,https://media.rawg.io/media/games/2ba/2bac0e87...
3,4291,Counter-Strike: Global Offensive,2012-08-21,3.57,PC|Linux|Xbox 360|PlayStation 3,Shooter,Steam Achievements|Multiplayer|Full controller...,https://media.rawg.io/media/games/736/73619bd3...
4,5286,Tomb Raider (2013),2013-03-05,4.06,PlayStation 3|Xbox 360|macOS|PC|Xbox One|PlayS...,Action,Singleplayer|Multiplayer|Full controller suppo...,https://media.rawg.io/media/games/021/021c4e21...
...,...,...,...,...,...,...,...,...
19995,20304,Fallen: A2P Protocol,2015-08-14,0.00,PlayStation 4|Linux|macOS|PC,RPG|Strategy|Indie,Singleplayer|Steam Achievements|Full controlle...,https://media.rawg.io/media/screenshots/2b6/2b...
19996,19999,MUD Motocross World Championship,2012-04-20,0.00,PlayStation 3|PS Vita|PC|Xbox 360,Simulation|Sports|Racing,Singleplayer|Steam Achievements|Multiplayer|St...,https://media.rawg.io/media/games/e34/e347ff3e...
19997,18168,Lepofrenia,2017-06-09,0.00,PC,Adventure|RPG|Indie,Singleplayer|Steam Achievements|steam-trading-...,https://media.rawg.io/media/screenshots/99b/99...
19998,17151,Fables from the Den,2016-10-26,0.00,macOS|PC|Linux,NaN,Design & Illustration,https://media.rawg.io/media/screenshots/389/38...
19999,17108,Mysterious Space,2015-05-15,0.00,PC,Action|Indie,Singleplayer|Steam Achievements|Full controlle...,https://media.rawg.io/media/screenshots/222/22...

In [118]:
df_req_cols_copy = df_req_cols.copy()

In [119]:
df_req_cols_copy

,id,name,released,rating,platforms,genres,tags,background_image
0,3498,Grand Theft Auto V,2013-09-17,4.47,PC|PlayStation 5|Xbox Series S/X|PlayStation 4...,Action,Singleplayer|Steam Achievements|Multiplayer|Fu...,https://media.rawg.io/media/games/20a/20aa03a1...
1,3328,The Witcher 3: Wild Hunt,2015-05-18,4.64,PlayStation 5|Xbox Series S/X|macOS|PlayStatio...,Action|RPG,Singleplayer|Full controller support|Atmospher...,https://media.rawg.io/media/games/618/618c2031...
2,4200,Portal 2,2011-04-18,4.58,PlayStation 3|PC|Xbox 360|Linux|macOS|Xbox One,Shooter|Puzzle,Singleplayer|Steam Achievements|Multiplayer|Fu...,https://media.rawg.io/media/games/2ba/2bac0e87...
3,4291,Counter-Strike: Global Offensive,2012-08-21,3.57,PC|Linux|Xbox 360|PlayStation 3,Shooter,Steam Achievements|Multiplayer|Full controller...,https://media.rawg.io/media/games/736/73619bd3...
4,5286,Tomb Raider (2013),2013-03-05,4.06,PlayStation 3|Xbox 360|macOS|PC|Xbox One|PlayS...,Action,Singleplayer|Multiplayer|Full controller suppo...,https://media.rawg.io/media/games/021/021c4e21...
...,...,...,...,...,...,...,...,...
19995,20304,Fallen: A2P Protocol,2015-08-14,0.00,PlayStation 4|Linux|macOS|PC,RPG|Strategy|Indie,Singleplayer|Steam Achievements|Full controlle...,https://media.rawg.io/media/screenshots/2b6/2b...
19996,19999,MUD Motocross World Championship,2012-04-20,0.00,PlayStation 3|PS Vita|PC|Xbox 360,Simulation|Sports|Racing,Singleplayer|Steam Achievements|Multiplayer|St...,https://media.rawg.io/media/games/e34/e347ff3e...
19997,18168,Lepofrenia,2017-06-09,0.00,PC,Adventure|RPG|Indie,Singleplayer|Steam Achievements|steam-trading-...,https://media.rawg.io/media/screenshots/99b/99...
19998,17151,Fables from the Den,2016-10-26,0.00,macOS|PC|Linux,NaN,Design & Illustration,https://media.rawg.io/media/screenshots/389/38...
19999,17108,Mysterious Space,2015-05-15,0.00,PC,Action|Indie,Singleplayer|Steam Achievements|Full controlle...,https://media.rawg.io/media/screenshots/222/22...

In [120]:
df_req_cols['tags'].iloc[0]

'Singleplayer|Steam Achievements|Multiplayer|Full controller support|Atmospheric|Great Soundtrack|RPG|Co-op|Open World|cooperative|First-Person|Third Person|Funny|Sandbox|Comedy|Third-Person Shooter|Moddable|Crime|vr mod'

In [121]:
def extract_tags(tags_info):

      if pd.isna(tags_info):
        return ""

      separated_tags = str(tags_info).split('|')
      new_taglist = []

      for tag in separated_tags:
        current_tags = tag.strip().lower()

        if 'single' in current_tags or 'multi' in current_tags:
            new_taglist.append(tag.strip())
      return ', '.join(new_taglist)
df_req_cols_copy['tags'] = df_req_cols_copy['tags'].apply(extract_tags)

In [122]:
df_req_cols_copy

,id,name,released,rating,platforms,genres,tags,background_image
0,3498,Grand Theft Auto V,2013-09-17,4.47,PC|PlayStation 5|Xbox Series S/X|PlayStation 4...,Action,"Singleplayer, Multiplayer",https://media.rawg.io/media/games/20a/20aa03a1...
1,3328,The Witcher 3: Wild Hunt,2015-05-18,4.64,PlayStation 5|Xbox Series S/X|macOS|PlayStatio...,Action|RPG,"Singleplayer, Multiple Endings",https://media.rawg.io/media/games/618/618c2031...
2,4200,Portal 2,2011-04-18,4.58,PlayStation 3|PC|Xbox 360|Linux|macOS|Xbox One,Shooter|Puzzle,"Singleplayer, Multiplayer",https://media.rawg.io/media/games/2ba/2bac0e87...
3,4291,Counter-Strike: Global Offensive,2012-08-21,3.57,PC|Linux|Xbox 360|PlayStation 3,Shooter,Multiplayer,https://media.rawg.io/media/games/736/73619bd3...
4,5286,Tomb Raider (2013),2013-03-05,4.06,PlayStation 3|Xbox 360|macOS|PC|Xbox One|PlayS...,Action,"Singleplayer, Multiplayer",https://media.rawg.io/media/games/021/021c4e21...
...,...,...,...,...,...,...,...,...
19995,20304,Fallen: A2P Protocol,2015-08-14,0.00,PlayStation 4|Linux|macOS|PC,RPG|Strategy|Indie,Singleplayer,https://media.rawg.io/media/screenshots/2b6/2b...
19996,19999,MUD Motocross World Championship,2012-04-20,0.00,PlayStation 3|PS Vita|PC|Xbox 360,Simulation|Sports|Racing,"Singleplayer, Multiplayer",https://media.rawg.io/media/games/e34/e347ff3e...
19997,18168,Lepofrenia,2017-06-09,0.00,PC,Adventure|RPG|Indie,Singleplayer,https://media.rawg.io/media/screenshots/99b/99...
19998,17151,Fables from the Den,2016-10-26,0.00,macOS|PC|Linux,NaN,,https://media.rawg.io/media/screenshots/389/38...
19999,17108,Mysterious Space,2015-05-15,0.00,PC,Action|Indie,"Singleplayer, Local Multiplayer",https://media.rawg.io/media/screenshots/222/22...

In [123]:
df_req_cols['tags'].iloc[0]

'Singleplayer|Steam Achievements|Multiplayer|Full controller support|Atmospheric|Great Soundtrack|RPG|Co-op|Open World|cooperative|First-Person|Third Person|Funny|Sandbox|Comedy|Third-Person Shooter|Moddable|Crime|vr mod'

In [124]:
extract_tags(df_req_cols_copy['tags'].iloc[0])

'Singleplayer, Multiplayer'

In [125]:
df_req_cols_copy.to_json("req_cols.json",orient='records',lines=False,indent=4,force_ascii=False)